baseURL = "http://www.mathcs.emory.edu/Research/Area/ScientificComputing/"
languageCode = "en-us"
title = "Emory Scientific Computing Group"
theme = "minimal"
#disqusShortname = "username" # delete this to disable disqus comments

[params]
    author = "Emory Scientific Computing"
    description = "Emory University Scientific Computing Group"
#    githubUsername = "#"
    accent = "#002878"
    showBorder = true
    backgroundColor = "white"
    font = "Roboto" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
#    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    copyright = "&copy; All rights reserved."

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/research/"
    name = "Research"
    weight = 2

[[menu.main]]
    url = "/software/"
    name = "Software"
    weight = 3

[[menu.main]]
    url = "/undergrad/"
    name = "Undergraduate"
    weight = 4

[[menu.main]]
    url = "/REURET/"
    name = "REU/RET"
    weight = 5


[[menu.main]]
    url = "/grad/"
    name = "Graduate"
    weight = 6

[[menu.main]]
    url = "/teaching/"
    name = "Teaching"
    weight = 7

[[menu.main]]
    url = "/schedule/"
    name = "Seminar"
    weight = 8

[[menu.main]]
    url = "/jobs/"
    name = "Jobs"
    weight = 9

[[menu.main]]
    url = "/people/"
    name = "People"
    weight = 10


# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

#[[menu.icon]]
#    url = "mailto:me@example.com"
#    name = "envelope-o"
#    weight = 1

[[menu.icon]]
    url = "https://github.com/lruthotto/EmorySciComp"
    name = "github"
    weight = 2

#[[menu.icon]]
#    url = "https://twitter.com/username/"
#    name = "twitter"
#    weight = 3

#[[menu.icon]]
#    url = "https://www.linkedin.com/in/username/"
#    name = "linkedin"
#    weight = 4

#[[menu.icon]]
#    url = "https://www.stackoverflow.com/username/"
#    name = "stack-overflow"
#    weight = 5
